-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 20:23:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema geek_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geek_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geek_project` DEFAULT CHARACTER SET utf8 ;
USE `geek_project` ;

-- -----------------------------------------------------
-- Table `geek_project`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geek_project`.`category` ;

CREATE TABLE IF NOT EXISTS `geek_project`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `geek_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geek_project`.`users` ;

CREATE TABLE IF NOT EXISTS `geek_project`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  UNIQUE INDEX `users_login_uindex` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `geek_project`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geek_project`.`order` ;

CREATE TABLE IF NOT EXISTS `geek_project`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) NOT NULL,
  `status` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `order_user_fk` (`user_id` ASC) VISIBLE,
  CONSTRAINT `order_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `geek_project`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `geek_project`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geek_project`.`product` ;

CREATE TABLE IF NOT EXISTS `geek_project`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `quantity` INT(11) NULL DEFAULT '1',
  `category_id` INT(11) NOT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  `img_min` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_category_fk` (`category_id` ASC) VISIBLE,
  CONSTRAINT `product_category_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `geek_project`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `geek_project`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geek_project`.`order_item` ;

CREATE TABLE IF NOT EXISTS `geek_project`.`order_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_item_product_fk` (`product_id` ASC) VISIBLE,
  INDEX `order_item_order_fk` (`order_id` ASC) VISIBLE,
  CONSTRAINT `order_item_order_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `geek_project`.`order` (`id`),
  CONSTRAINT `order_item_product_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `geek_project`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `geek_project`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geek_project`.`reviews` ;

CREATE TABLE IF NOT EXISTS `geek_project`.`reviews` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `geek_project`.`prices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geek_project`.`prices` ;

CREATE TABLE IF NOT EXISTS `geek_project`.`prices` (
  `id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `discount` INT(11) NULL,
  `summer_discount` INT(11) NULL,
  `winter_discount` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id_category_fk_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id_category_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `geek_project`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
